export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_SAGA = "AUTH_SAGA";
export const AUTH_START = "AUTH_START";
export const AUTH_FAIL = "AUTH_FAIL";

export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_SAGA = "GET_PRODUCT_SAGA";
export const GET_PRODUCT_START = "GET_PRODUCT_START";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";

export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_SAGA = "ADD_CART_SAGA";
export const ADD_CART_START = "ADD_CART_START";
export const ADD_CART_FAIL = "ADD_CART_FAIL";

export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_SAGA = "GET_CART_SAGA";
export const GET_CART_START = "GET_CART_START";
export const GET_CART_FAIL = "GET_CART_FAIL";

export const GET_PRODUCT_SORT_SUCCESS = "GET_PRODUCT_SORT_SUCCESS";
export const GET_PRODUCT_SORT_SAGA = "GET_PRODUCT_SORT_SAGA";
export const GET_PRODUCT_SORT_START = "GET_PRODUCT_SORT_START";
export const GET_PRODUCT_SORT_FAIL = "GET_PRODUCT_FAIL";
